version: '3'
services:
  api:
    image: "ultimatettt/ultimate-ttt-server:localtesting"
    ports:
     - "5023:80"
    depends_on:
      - 'mongo'
    environment:
     - Database:Name=ultimate-ttt
     - Database:ConnectionString=mongodb://mongo/

  mongo:
    image: 'mongo:latest'
    ports:
      - '27018:27017'
